### ISSUE TITLE
TypeError: Not a Bufffer

### ISSUE THREAD

**Issue by mdramos** [madhurjain/passport-local-sequelize#25]
Route code:
```
router.get('/login', passport.authenticate('local'), function(req, res) {
  res.render('index');
});
```
After submitting a correct login, I get this. 

Stack Trace:
```
Unhandled rejection TypeError: Not a buffer
    at TypeError (native)
    at pbkdf2 (crypto.js:562:20)
    at Object.exports.pbkdf2 (crypto.js:548:10)
    at UserSchema.Instance.authenticate (/Users/.../node_modules/passport-local-sequelize/lib/passport-local-sequelize.js:126:16)
    at /Users/.../node_modules/passport-local-sequelize/lib/passport-local-sequelize.js:148:33
    at null.<anonymous> (/Users/.../node_modules/passport-local-sequelize/lib/passport-local-sequelize.js:258:13)
    at tryCatcher (/Users/.../node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/.../node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/.../node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/.../node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/.../node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/.../node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/.../node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/.../node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by mdramos** [comment]
fields need to be hashed if using hashed fields
